name: BMP-Welcome
version: 0.0.5
main: ru.blockmania.bmpwelcome.BMP_Welcome
api-version: '1.16'
author: BlockMania
softdepend: [PlaceholderAPI]
commands:
  welcome:
    description: "Перезагрузка конфига"